"""
Coding Meetup #17 - Higher-Order Functions Series - Sort by programming language.

You will be given an array of objects representing data about developers who
have signed up to attend the next coding meetup that you are organising.

Given the following input array:

arr1 = [{'age': 29,
         'continent': 'Europe',
         'country': 'Belarus',
         'first_name': 'Kseniya',
         'language': 'JavaScript',
         'last_name': 'A.'},
        {'age': 39,
         'continent': 'Asia',
         'country': 'China',
         'first_name': 'Jing',
         'language': 'Ruby',
         'last_name': 'X.'},
        {'age': 59,
         'continent': 'Europe',
         'country': 'Romania',
         'first_name': 'Andrei',
         'language': 'C',
         'last_name': 'E.'},
        {'age': 60,
         'continent': 'Americas',
         'country': 'Peru',
         'first_name': 'Maria',
         'language': 'C',
         'last_name': 'S.'},
        {'age': 88,
         'continent': 'Europe',
         'country': 'Guernsey',
         'first_name': 'Chloe',
         'language': 'Ruby',
         'last_name': 'K.'},
        {'age': 98,
         'continent': 'Europe',
         'country': 'Bulgaria',
         'first_name': 'Viktoria',
         'language': 'PHP',
         'last_name': 'W.'},
        {'age': 128,
         'continent': 'Europe',
         'country': 'Poland',
         'first_name': 'Piotr',
         'language': 'JavaScript',
         'last_name': 'B.'}]

write a function that returns the array sorted alphabetically by the programming language.
In case there are some developers that code in the same language, sort them
alphabetically by the first name:

exp_arr1 = [{'age': 59,
             'continent': 'Europe',
             'country': 'Romania',
             'first_name': 'Andrei',
             'language': 'C',
             'last_name': 'E.'},
            {'age': 60,
             'continent': 'Americas',
             'country': 'Peru',
             'first_name': 'Maria',
             'language': 'C',
             'last_name': 'S.'},
            {'age': 29,
             'continent': 'Europe',
             'country': 'Belarus',
             'first_name': 'Kseniya',
             'language': 'JavaScript',
             'last_name': 'A.'},
            {'age': 128,
             'continent': 'Europe',
             'country': 'Poland',
             'first_name': 'Piotr',
             'language': 'JavaScript',
             'last_name': 'B.'},
            {'age': 98,
             'continent': 'Europe',
             'country': 'Bulgaria',
             'first_name': 'Viktoria',
             'language': 'PHP',
             'last_name': 'W.'},
            {'age': 88,
             'continent': 'Europe',
             'country': 'Guernsey',
             'first_name': 'Chloe',
             'language': 'Ruby',
             'last_name': 'K.'},
            {'age': 39,
             'continent': 'Asia',
             'country': 'China',
             'first_name': 'Jing',
             'language': 'Ruby',
             'last_name': 'X.'}]
"""
import sys

sys.path.append('..')
from helpers.test_wrapper import Test


def sort_by_language(arr):
    return sorted(arr, key=lambda k: (k['language'], k['first_name']))


def run_tests():
    with Test() as test:
        test.describe("Basic tests")
        arr1 = [{'age': 29,
                 'continent': 'Europe',
                 'country': 'Belarus',
                 'first_name': 'Kseniya',
                 'language': 'JavaScript',
                 'last_name': 'A.'},
                {'age': 39,
                 'continent': 'Asia',
                 'country': 'China',
                 'first_name': 'Jing',
                 'language': 'Ruby',
                 'last_name': 'X.'},
                {'age': 59,
                 'continent': 'Europe',
                 'country': 'Romania',
                 'first_name': 'Andrei',
                 'language': 'C',
                 'last_name': 'E.'},
                {'age': 60,
                 'continent': 'Americas',
                 'country': 'Peru',
                 'first_name': 'Maria',
                 'language': 'C',
                 'last_name': 'S.'},
                {'age': 88,
                 'continent': 'Europe',
                 'country': 'Guernsey',
                 'first_name': 'Chloe',
                 'language': 'Ruby',
                 'last_name': 'K.'},
                {'age': 98,
                 'continent': 'Europe',
                 'country': 'Bulgaria',
                 'first_name': 'Viktoria',
                 'language': 'PHP',
                 'last_name': 'W.'},
                {'age': 128,
                 'continent': 'Europe',
                 'country': 'Poland',
                 'first_name': 'Piotr',
                 'language': 'JavaScript',
                 'last_name': 'B.'}]

        arr2 = [{'age': 19,
                 'continent': 'Americas',
                 'country': 'Brazil',
                 'first_name': 'Paulo',
                 'language': 'Python',
                 'last_name': 'K.'}]

        arr3 = [{'age': 39,
                 'continent': 'Oceania',
                 'country': 'New Zealand',
                 'first_name': 'Nikau',
                 'language': 'Ruby',
                 'last_name': 'R.'},
                {'age': 22,
                 'continent': 'Africa',
                 'country': 'South Africa',
                 'first_name': 'Precious',
                 'language': 'JavaScript',
                 'last_name': 'G.'},
                {'age': 30,
                 'continent': 'Americas',
                 'country': 'Peru',
                 'first_name': 'Maria',
                 'language': 'C',
                 'last_name': 'S.'},
                {'age': 19,
                 'continent': 'Americas',
                 'country': 'Uruguay',
                 'first_name': 'Agustin',
                 'language': 'JavaScript',
                 'last_name': 'V.'}]
        arr4 = [{'age': 39,
                 'continent': 'Oceania',
                 'country': 'New Zealand',
                 'first_name': 'Nikau',
                 'language': 'Ruby',
                 'last_name': 'R.'},
                {'age': 30,
                 'continent': 'Americas',
                 'country': 'Peru',
                 'first_name': 'Maria',
                 'language': 'C',
                 'last_name': 'S.'},
                {'age': 19,
                 'continent': 'Americas',
                 'country': 'Uruguay',
                 'first_name': 'Agustin',
                 'language': 'JavaScript',
                 'last_name': 'V.'}]

        arr5 = arr4 + arr3

        exp_arr1 = [{'age': 59,
                     'continent': 'Europe',
                     'country': 'Romania',
                     'first_name': 'Andrei',
                     'language': 'C',
                     'last_name': 'E.'},
                    {'age': 60,
                     'continent': 'Americas',
                     'country': 'Peru',
                     'first_name': 'Maria',
                     'language': 'C',
                     'last_name': 'S.'},
                    {'age': 29,
                     'continent': 'Europe',
                     'country': 'Belarus',
                     'first_name': 'Kseniya',
                     'language': 'JavaScript',
                     'last_name': 'A.'},
                    {'age': 128,
                     'continent': 'Europe',
                     'country': 'Poland',
                     'first_name': 'Piotr',
                     'language': 'JavaScript',
                     'last_name': 'B.'},
                    {'age': 98,
                     'continent': 'Europe',
                     'country': 'Bulgaria',
                     'first_name': 'Viktoria',
                     'language': 'PHP',
                     'last_name': 'W.'},
                    {'age': 88,
                     'continent': 'Europe',
                     'country': 'Guernsey',
                     'first_name': 'Chloe',
                     'language': 'Ruby',
                     'last_name': 'K.'},
                    {'age': 39,
                     'continent': 'Asia',
                     'country': 'China',
                     'first_name': 'Jing',
                     'language': 'Ruby',
                     'last_name': 'X.'}]

        exp_arr2 = [{'age': 19,
                     'continent': 'Americas',
                     'country': 'Brazil',
                     'first_name': 'Paulo',
                     'language': 'Python',
                     'last_name': 'K.'}]

        exp_arr3 = [{'age': 30,
                     'continent': 'Americas',
                     'country': 'Peru',
                     'first_name': 'Maria',
                     'language': 'C',
                     'last_name': 'S.'},
                    {'age': 19,
                     'continent': 'Americas',
                     'country': 'Uruguay',
                     'first_name': 'Agustin',
                     'language': 'JavaScript',
                     'last_name': 'V.'},
                    {'age': 22,
                     'continent': 'Africa',
                     'country': 'South Africa',
                     'first_name': 'Precious',
                     'language': 'JavaScript',
                     'last_name': 'G.'},
                    {'age': 39,
                     'continent': 'Oceania',
                     'country': 'New Zealand',
                     'first_name': 'Nikau',
                     'language': 'Ruby',
                     'last_name': 'R.'}]

        exp_arr4 = [{'age': 30,
                     'continent': 'Americas',
                     'country': 'Peru',
                     'first_name': 'Maria',
                     'language': 'C',
                     'last_name': 'S.'},
                    {'age': 19,
                     'continent': 'Americas',
                     'country': 'Uruguay',
                     'first_name': 'Agustin',
                     'language': 'JavaScript',
                     'last_name': 'V.'},
                    {'age': 39,
                     'continent': 'Oceania',
                     'country': 'New Zealand',
                     'first_name': 'Nikau',
                     'language': 'Ruby',
                     'last_name': 'R.'}]

        exp_arr5 = [{'age': 30,
                     'continent': 'Americas',
                     'country': 'Peru',
                     'first_name': 'Maria',
                     'language': 'C',
                     'last_name': 'S.'},
                    {'age': 30,
                     'continent': 'Americas',
                     'country': 'Peru',
                     'first_name': 'Maria',
                     'language': 'C',
                     'last_name': 'S.'},
                    {'age': 19,
                     'continent': 'Americas',
                     'country': 'Uruguay',
                     'first_name': 'Agustin',
                     'language': 'JavaScript',
                     'last_name': 'V.'},
                    {'age': 19,
                     'continent': 'Americas',
                     'country': 'Uruguay',
                     'first_name': 'Agustin',
                     'language': 'JavaScript',
                     'last_name': 'V.'},
                    {'age': 22,
                     'continent': 'Africa',
                     'country': 'South Africa',
                     'first_name': 'Precious',
                     'language': 'JavaScript',
                     'last_name': 'G.'},
                    {'age': 39,
                     'continent': 'Oceania',
                     'country': 'New Zealand',
                     'first_name': 'Nikau',
                     'language': 'Ruby',
                     'last_name': 'R.'},
                    {'age': 39,
                     'continent': 'Oceania',
                     'country': 'New Zealand',
                     'first_name': 'Nikau',
                     'language': 'Ruby',
                     'last_name': 'R.'}]

        test.assert_equals(sort_by_language(arr1), exp_arr1)
        test.assert_equals(sort_by_language(arr2), exp_arr2)
        test.assert_equals(sort_by_language(arr3), exp_arr3)
        test.assert_equals(sort_by_language(arr4), exp_arr4)
        test.assert_equals(sort_by_language(arr5), exp_arr5)


if __name__ == '__main__':
    run_tests()
